(* let test_get_num () = *)
(*   let check_ok input index expected = *)
(*     match Json_ml.get_num input index with *)
(*     | Ok v when v = expected -> () (* exact match *) *)
(*     | Ok v -> *)
(*         Printf.printf "Test failed: input=%S index=%d, expected=%f, got=%f\n" *)
(*           input index expected v *)
(*     | Error msg -> *)
(*         Printf.printf *)
(*           "Test failed: input=%S index=%d, expected=%f, got Error %s\n" input *)
(*           index expected msg *)
(*   in *)
(*   let check_error input index = *)
(*     match Json_ml.get_num input index with *)
(*     | Ok v -> *)
(*         Printf.printf "Test failed: input=%S index=%d, expected Error, got %f\n" *)
(*           input index v *)
(*     | Error _ -> () (* passed, got an error as expected *) *)
(*   in *)
(**)
(*   check_error "h123h" 0; *)
(*   check_ok "h123h" 1 123.0; *)
(*   check_ok "h123" 1 123.0; *)
(**)
(*   print_endline "done testing" *)
(**)
(* let () = test_get_num () *)
